// <auto-generated />
using System;
using Animals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animals.Migrations
{
    [DbContext(typeof(AnimalsContext))]
    partial class AnimalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animals.Models.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AnimalClassID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AnimalClassID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Animal", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdmissionDate = new DateTime(2020, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalClassID = 3,
                            Name = "nameAnimal1",
                            OwnerID = 1
                        },
                        new
                        {
                            ID = 2,
                            AdmissionDate = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalClassID = 2,
                            Name = "nameAnimal2",
                            OwnerID = 2
                        },
                        new
                        {
                            ID = 3,
                            AdmissionDate = new DateTime(2022, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalClassID = 2,
                            Name = "nameAnimal3",
                            OwnerID = 2
                        });
                });

            modelBuilder.Entity("Animals.Models.AnimalClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Animal_Class", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "nameclass1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "nameclass2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "nameclass3"
                        });
                });

            modelBuilder.Entity("Animals.Models.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Owner", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Anna",
                            LastName = "Kowal"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Michał",
                            LastName = "Kowalczyk"
                        });
                });

            modelBuilder.Entity("Animals.Models.Procedure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Procedure", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "procedure-desc",
                            Name = "procedure-name"
                        },
                        new
                        {
                            ID = 2,
                            Description = "procedure-desc-2",
                            Name = "procedure-name-2"
                        });
                });

            modelBuilder.Entity("Animals.Models.ProcedureAnimal", b =>
                {
                    b.Property<int>("ProcedureID")
                        .HasColumnType("int");

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ProcedureID", "AnimalID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Procedure_Animal", (string)null);

                    b.HasData(
                        new
                        {
                            ProcedureID = 1,
                            AnimalID = 1,
                            Date = new DateTime(2020, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureID = 2,
                            AnimalID = 2,
                            Date = new DateTime(2020, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureID = 1,
                            AnimalID = 3,
                            Date = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Animals.Models.Animal", b =>
                {
                    b.HasOne("Animals.Models.AnimalClass", "AnimalClass")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animals.Models.Owner", "Owner")
                        .WithMany("Animals")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalClass");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Animals.Models.ProcedureAnimal", b =>
                {
                    b.HasOne("Animals.Models.Animal", "Animal")
                        .WithMany("ProcedureAnimals")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animals.Models.Procedure", "Procedure")
                        .WithMany("ProcedureAnimals")
                        .HasForeignKey("ProcedureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("Animals.Models.Animal", b =>
                {
                    b.Navigation("ProcedureAnimals");
                });

            modelBuilder.Entity("Animals.Models.AnimalClass", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Animals.Models.Owner", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Animals.Models.Procedure", b =>
                {
                    b.Navigation("ProcedureAnimals");
                });
#pragma warning restore 612, 618
        }
    }
}
